spring:
  application:
    name: TradeSim

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

brapi:
  url: https://brapi.dev/api/
  token: ${BRAPI_API_KEY}

api:
  security:
    token:
      secret: ${JWT_SECRET}