package br.com.pedrolourenco.TradeSim.controller;

import br.com.pedrolourenco.TradeSim.controller.request.DateRangeRequest;
import br.com.pedrolourenco.TradeSim.controller.response.*;
import br.com.pedrolourenco.TradeSim.domain.transaction.*;
import br.com.pedrolourenco.TradeSim.domain.user.User;
import br.com.pedrolourenco.TradeSim.exception.UnprocessableDataException;
import br.com.pedrolourenco.TradeSim.mapper.BalanceTransactionMapper;
import br.com.pedrolourenco.TradeSim.mapper.TransactionMapper;
import br.com.pedrolourenco.TradeSim.security.CustomUserDetails;
import br.com.pedrolourenco.TradeSim.service.TransactionOrchestratorService;
import br.com.pedrolourenco.TradeSim.service.TransactionService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Map;

@RestController
@RequestMapping("/transactions")
@RequiredArgsConstructor
@Tag(name = "Transaction", description = """
        Endpoints for creating and listing transactions.

        ### Idempotency Key
        The Idempotency-Key is a UUID generated by the client for every new request to ensure safe retries.

        **How it works:**
        - **Header:** Include the `Idempotency-Key` header with a unique UUID.
        - **Missing/Invalid Key:** Requests without a valid UUID will return a `400 Bad Request`.
        - **Processing:** If a request is repeated while the original is still processing, a `409 Conflict` is returned.
        - **Completed:** If a request is repeated after completion, the cached response of the original request is returned.
        - **Errors:** If the original request failed with a `400`, the retry will be processed again (no cache).
        """)
public class TransactionController {
    private final TransactionService transactionService;

    private final TransactionOrchestratorService transactionOrchestratorService;

    private final TransactionMapper transactionMapper;

    private final BalanceTransactionMapper balanceTransactionMapper;

    private static final Map<String, String> SORT_FIELDS = Map.of(
            "transactionType", "type",
            "transactionTime", "createdAt",
            "stockTicker",     "stock.ticker",
            "amount",          "amount"
    );

    @GetMapping()
    @Operation(
            summary = "List transactions",
            description = """
            Retrieves a paginated list of transactions for the authenticated user within a specific date range.

            **🔒 Endpoint protected — requires JWT authentication.**
            
            **Sorting:**
            You can sort the results using the `sort` parameter. The available fields are:
            - `transactionType`
            - `transactionTime`
            - `stockTicker`
            - `amount`
            
            Example: `sort=transactionTime,desc` or `sort=amount,asc`.
            """,
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Transactions retrieved successfully"),
            @ApiResponse(responseCode = "422", description = "Invalid date range or invalid sort field",
                    content = @Content(
                            schema = @Schema(implementation = BasicResponse.class),
                            examples = @ExampleObject(value = """
                            {
                              "error": true,
                              "message": "The start date must be equal to or later than the end date"
                            }
                            """)
                    ))
    })
    public ResponseEntity<PagedDataResponse<TransactionOutputDTO>> list(@Valid @ModelAttribute DateRangeRequest dateRange,
                                                                        @PageableDefault(page = 0, size = 10, direction = Sort.Direction.ASC) Pageable pageable){
        LocalDate startDate = LocalDate.parse(dateRange.startDate());
        LocalDate endDate = LocalDate.parse(dateRange.endDate());

        if (startDate.isAfter(endDate)) {
            throw new UnprocessableDataException("The start date must be equal to or later than the end date");
        }

        if(endDate.isAfter(LocalDate.now())){
            throw new UnprocessableDataException("Both dates must be in the present or past");
        }

        Page<TransactionOutputDTO> page = transactionService.list(
                getAuthenticatedUser().getId(),
                translateSort(pageable),
                startDate,
                endDate)
                .map(transactionMapper::toDTO);

        PageMetadata metadata = new PageMetadata(
                page.getNumber(),
                page.getSize(),
                page.getNumberOfElements(),
                page.getTotalElements(),
                page.getTotalPages(),
                page.isFirst(),
                page.isLast(),
                page.hasNext(),
                page.hasPrevious()
        );

        String message = page.getNumberOfElements() == 0 ?
                "No transactions found" : "transactions found";

        PagedDataResponse<TransactionOutputDTO> response = new PagedDataResponse<>(
                false,
                message,
                metadata,
                page.getContent()
        );

        return ResponseEntity.ok(response);
    }

    @PostMapping("/deposit")
    @Operation(
            summary = "Deposit funds",
            description = "Deposits funds into the user's account.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @Parameter(name = "Idempotency-Key", description = "UUID for idempotency", required = true, in = ParameterIn.HEADER)
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Deposit successful"),
            @ApiResponse(responseCode = "400", description = "Invalid input data",
                    content = @Content(
                            schema = @Schema(implementation = FieldsErrorResponse.class),
                            examples = @ExampleObject(value = """
                            {
                              "error": true,
                              "message": "Invalid fields",
                              "fields": {
                                "amount": "amount is missing"
                              }
                            }
                            """)
                    ))
    })
    public ResponseEntity<DataResponse<BalanceTransactionOutputDTO>> deposit(@RequestBody @Valid BalanceTransactionInputDTO amount){
        Transaction transaction = transactionOrchestratorService.deposit(getAuthenticatedUser(), new BigDecimal(amount.getAmount()));

        DataResponse<BalanceTransactionOutputDTO> response = new DataResponse<>(
                false,
                "deposit successful",
                balanceTransactionMapper.toDTO(transaction)
        );

        return ResponseEntity.ok(response);
    }

    @PostMapping("/withdraw")
    @Operation(
            summary = "Withdraw funds",
            description = "Withdraws funds from the user's account.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @Parameter(name = "Idempotency-Key", description = "UUID for idempotency", required = true, in = ParameterIn.HEADER)
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Withdrawal successful"),
            @ApiResponse(responseCode = "400", description = "Invalid input data",
                    content = @Content(
                            schema = @Schema(implementation = FieldsErrorResponse.class),
                            examples = @ExampleObject(value = """
                            {
                              "error": true,
                              "message": "Invalid fields",
                              "fields": {
                                "amount": "Must be a number with up to 2 decimal places"
                              }
                            }
                            """)
                    )),
            @ApiResponse(responseCode = "422", description = "Insufficient balance",
                    content = @Content(
                            schema = @Schema(implementation = BasicResponse.class),
                            examples = @ExampleObject(value = """
                            {
                              "error": true,
                              "message": "Insufficient balance"
                            }
                            """)
                    ))
    })
    public ResponseEntity<DataResponse<BalanceTransactionOutputDTO>> withdraw(@RequestBody @Valid BalanceTransactionInputDTO amount){
        Transaction transaction = transactionOrchestratorService.withdraw(getAuthenticatedUser(), new BigDecimal(amount.getAmount()));

        DataResponse<BalanceTransactionOutputDTO> response = new DataResponse<>(
                false,
                "withdrawal successful",
                balanceTransactionMapper.toDTO(transaction)
        );

        return ResponseEntity.ok(response);
    }

    @PostMapping("/buy/{ticker}")
    @Operation(
            summary = "Buy stock",
            description = "Purchases a specific quantity of a stock.",
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @Parameter(name = "Idempotency-Key", description = "UUID for idempotency", required = true, in = ParameterIn.HEADER)
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Stock purchased successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid input data",
                    content = @Content(
                            schema = @Schema(implementation = FieldsErrorResponse.class),
                            examples = @ExampleObject(value = """
                            {
                              "error": true,
                              "message": "Invalid fields",
                              "fields": {
                                "quantity": "quantity is missing"
                              }
                            }
                            """)
                    )),
            @ApiResponse(responseCode = "404", description = "Stock not found",
                    content = @Content(
                            schema = @Schema(implementation = BasicResponse.class),
                            examples = @ExampleObject(value = """
                            {
                              "error": true,
                              "message": "This stock is not available on this platform"
                            }
                            """)
                    )),
            @ApiResponse(responseCode = "422", description = "Insufficient balance",
                    content = @Content(
                            schema = @Schema(implementation = BasicResponse.class),
                            examples = @ExampleObject(value = """
                            {
                              "error": true,
                              "message": "Insufficient balance to complete the purchase"
                            }
                            """)
                    ))
    })
    public ResponseEntity<DataResponse<TransactionOutputDTO>> buyStock(@PathVariable String ticker,
                                                                       @RequestBody @Valid StockTransactionInputDTO quantity){
        Transaction transaction = transactionOrchestratorService.buyStock(getAuthenticatedUser(), ticker, Long.parseLong(quantity.getQuantity()));

        DataResponse<TransactionOutputDTO> response = new DataResponse<>(
                false,
                "stock purchased",
                transactionMapper.toDTO(transaction));

        return ResponseEntity.ok(response);
    }

    @PostMapping("sell/{ticker}")
    @Operation(
            summary = "Sell stock",
            description = """
            Sells a specific quantity of a stock owned by the user.
            
            **Note:** A fee is charged on sales, simulating real market conditions: B3 fee (0.03%) + IRRF (0.005%).
            """,
            security = @SecurityRequirement(name = "bearerAuth")
    )
    @Parameter(name = "Idempotency-Key", description = "UUID for idempotency", required = true, in = ParameterIn.HEADER)
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Stock sold successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid input data",
                    content = @Content(
                            schema = @Schema(implementation = FieldsErrorResponse.class),
                            examples = @ExampleObject(value = """
                            {
                              "error": true,
                              "message": "Invalid fields",
                              "fields": {
                                "quantity": "Must be a positive integer"
                              }
                            }
                            """)
                    )),
            @ApiResponse(responseCode = "404", description = "Stock not found",
                    content = @Content(
                            schema = @Schema(implementation = BasicResponse.class),
                            examples = @ExampleObject(value = """
                            {
                              "error": true,
                              "message": "This stock is not available on this platform"
                            }
                            """)
                    )),
            @ApiResponse(responseCode = "422", description = "Insufficient quantity of stocks",
                    content = @Content(
                            schema = @Schema(implementation = BasicResponse.class),
                            examples = @ExampleObject(value = """
                            {
                              "error": true,
                              "message": "Insufficient stock quantity"
                            }
                            """)
                    ))
    })
    public ResponseEntity<DataResponse<TransactionOutputDTO>> sellStock(@PathVariable String ticker,
                                                                       @RequestBody @Valid StockTransactionInputDTO quantity){
        Transaction transaction = transactionOrchestratorService.sellStock(getAuthenticatedUser(), ticker, Long.parseLong(quantity.getQuantity()));

        DataResponse<TransactionOutputDTO> response = new DataResponse<>(
                false,
                "stock sold",
                transactionMapper.toDTO(transaction));

        return ResponseEntity.ok(response);
    }

    private User getAuthenticatedUser(){
        CustomUserDetails userDetails = (CustomUserDetails) SecurityContextHolder.getContext().getAuthentication().getPrincipal();

        User user = new User();
        user.setId(userDetails.getId());

        return user;
    }

    private Pageable translateSort(Pageable pageable) {
        return PageRequest.of(
                pageable.getPageNumber(),
                pageable.getPageSize(),
                Sort.by(pageable.getSort().stream()
                        .map(o -> {
                            String property = SORT_FIELDS.get(o.getProperty());
                            if(property == null){
                                throw new UnprocessableDataException("invalid sort field");
                            }

                            return o.withProperty(property);
                        })
                        .toList())
        );
    }
}
